### ISSUE TITLE
[Home Cameras] BlinkException [Error]: Can't retrieve system status

### ISSUE THREAD

**Issue by monteroman** [jasmas/homebridge-platform-blink-security#8]
I've started seeing this in the logs and the Blink camera sync module no longer initializes.

[Home Cameras] BlinkException [Error]: Can't retrieve system status
    at Request._callback (/usr/lib/node_modules/homebridge-platform-blink-security/node_modules/node-blink-security/
lib/blink.js:348:18)
    at self.callback (/usr/lib/node_modules/homebridge-platform-blink-security/node_modules/request/request.js:186:2
2)
    at Request.emit (events.js:196:13)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-platform-blink-security/node_modules/request/request
.js:878:8)
    at ClientRequest.emit (events.js:196:13)
    at TLSSocket.socketErrorListener (_http_client.js:409:9)
    at TLSSocket.emit (events.js:196:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

I have 2 modules, but the name, I tell it to use the one named "Home Cameras".    Thoughts?

**Comment by jasmas** [comment]
Are you still having this issue?
